import express from 'express';

const router = express.Router();

export default function createApiRoutes(invoiceGenerator, statusMonitor, lightningClient, donationTracker, mavaPayClient) {

    // POST /api/invoice - Create a new lightning invoice
    router.post('/invoice', async (req, res, next) => {
        try {
            const { amount, description } = req.body;

            // Basic validation
            if (!amount || amount < 1) {
                return res.status(400).json({ error: 'Amount must be a positive integer' });
            }

            // Generate invoice
            const invoice = await invoiceGenerator.generateInvoice({
                amount: parseInt(amount),
                description: description || 'Donation'
            });

            // Create donation record
            const donation = await donationTracker.createDonation({
                paymentHash: invoice.paymentHash,
                amount: parseInt(amount),
                description: description || 'Donation',
                paymentRequest: invoice.paymentRequest,
                expiresAt: invoice.expiresAt
            });

            res.status(201).json({
                payment_request: invoice.paymentRequest,
                r_hash: invoice.paymentHash,
                amount: invoice.amount,
                expires_at: invoice.expiresAt
            });

        } catch (error) {
            next(error);
        }
    });

    // GET /api/invoice/:paymentHash - Check invoice status
    router.get('/invoice/:paymentHash', async (req, res, next) => {
        try {
            const { paymentHash } = req.params;

            // Check status using StatusMonitor
            // Note: StatusMonitor.checkPaymentStatus returns { status, donation }
            const statusResult = await statusMonitor.checkPaymentStatus(paymentHash);

            if (!statusResult || !statusResult.donation) {
                return res.status(404).json({ error: 'Invoice not found' });
            }

            res.json({
                settled: statusResult.status === 'completed',
                status: statusResult.status,
                preimage: statusResult.donation.preimage,
                payment_request: statusResult.donation.paymentRequest
            });

        } catch (error) {
            next(error);
        }
    });

    // GET /api/node - Get LND node info
    router.get('/node', async (req, res, next) => {
        try {
            const info = await lightningClient.getNodeInfo();
            res.json(info);
        } catch (error) {
            next(error);
        }
    });

    // --- MavaPay Off-ramp Routes ---

    // GET /api/banks/:country
    router.get('/banks/:country', async (req, res, next) => {
        try {
            const { country } = req.params;
            const banks = await mavaPayClient.getBanks(country.toUpperCase());
            res.json(banks);
        } catch (error) {
            next(error);
        }
    });

    // POST /api/offramp/quote
    router.post('/offramp/quote', async (req, res, next) => {
        try {
            const { amount, bankName, accountNumber, accountName } = req.body;

            // 1. Get Quote from MavaPay
            const quote = await mavaPayClient.getQuote({
                amount: amount * 100, // Convert Rand to Cents
                bankId: bankName,
                bankAccountNumber: accountNumber,
                accountName: accountName
            });

            if (!quote || !quote.invoice) {
                throw new Error("Failed to generate quote from MavaPay");
            }

            // 2. We don't need to create a donation record for off-ramp via LND directly 
            //    because the invoice is generated by MavaPay (hold invoice?)
            //    However, to track it in our system, we might want to store it.
            //    For now, let's just return the quote to the frontend.

            res.json({
                id: quote.id,
                payment_request: quote.invoice,
                amount_sats: quote.amountInSourceCurrency,
                amount_fiat: quote.amountInTargetCurrency,
                exchange_rate: quote.exchangeRate,
                expiry: quote.expiry,
                r_hash: quote.paymentHash // MavaPay might not return this immediately, checking docs...
                // If MavaPay doc example doesn't show r_hash, we might need to decode the invoice.
                // Logic can be added here if needed.
            });

        } catch (error) {
            next(error);
        }
    });


    return router;
}
